"""Protected access to uploaded document assets.

Branding files are intentionally public and remain mounted separately in
``main.py``.  Document images are knowledge-base data, so serving them must go
through the same capability and object-scope checks as document content.
"""

from __future__ import annotations

import re
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from config import get_settings
from core.deps import ensure_kb_access, require_permission
from core.permissions import DOC_READ
from database import get_db
from models.db_models import Document, User

router = APIRouter(prefix="/uploads", tags=["uploads"])

_IMAGE_FILENAME_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
    r"\.(?:png|jpe?g|webp|gif|bmp)$",
    re.IGNORECASE,
)


def _image_url(filename: str) -> str:
    return f"/api/uploads/images/{filename}"


def _resolve_image_path(filename: str) -> Path:
    """Resolve only filenames generated by the image-upload endpoint."""
    if not _IMAGE_FILENAME_PATTERN.fullmatch(filename):
        raise HTTPException(status_code=404, detail="图片不存在")

    image_dir = (Path(get_settings().upload_dir) / "images").resolve()
    candidate = (image_dir / filename).resolve()
    if candidate.parent != image_dir:
        raise HTTPException(status_code=404, detail="图片不存在")
    return candidate


@router.get("/images/{filename}", response_class=FileResponse)
async def get_document_image(
    filename: str,
    db: AsyncSession = Depends(get_db),
    user: User = Depends(require_permission(DOC_READ)),
):
    """Return an original document image after capability and KB-scope checks."""
    image_path = _resolve_image_path(filename)
    document = (await db.execute(
        select(Document).where(Document.image_url == _image_url(filename)).limit(1)
    )).scalars().first()
    if document is None or not image_path.is_file():
        raise HTTPException(status_code=404, detail="图片不存在")

    await ensure_kb_access(user, document.kb_id, db)
    return FileResponse(
        image_path,
        filename=filename,
        content_disposition_type="inline",
        headers={"Cache-Control": "private, max-age=300"},
    )
